# temporary makefile for syntax
SHELL := /bin/bash

# Compiler and flags
CXX = g++
CXXFLAGS = -g -Wall -Wextra -std=c++20 -Wno-unused-parameter -Werror

# Executable name
EXEC = compare

# Phase 1 
P1_DIR = Phase-1
P1_OBJ_DIR= Phase-1/obj
P1_SRCS := $(wildcard $(P1_DIR)/*.cpp)
P1_OBJS = $(P1_SRCS:$(P1_DIR)/%.cpp=$(P1_OBJ_DIR)/%.o)
Objects_Phase2 = /obj/graph.o ShortestPath.o KNN.o main.o



phase1: p1_generate_testcases $(P1_OBJS) 
	@$(CXX) $(CXXFLAGS) -o phase1 $(P1_OBJS)
	@echo "Phase 1 executable successfully built"
$(P1_OBJ_DIR)/%.o: $(P1_DIR)/%.cpp $(wildcard $(P1_DIR)/*.h)
	@mkdir -p $(dir $@)
	@$(CXX) $(CXXFLAGS) -c $< -o $@
p1_generate_testcases:
	@python3 $(P1_DIR)/testcase_generator.py


# Phase 2
phase2:




# Phase 3
phase3:



# Clean target
clean:
	rm phase1 phase2 phase3
	rm $(P1_OBJ_DIR)/*
	rm $(P2_OBJ_DIR)/*
	rm $(P3_OBJ_DIR)/*

.PHONY: phase1 phase2 phase3 p1_generate_testcases clean 

